### ISSUE TITLE
Use of stage wildcard for periodwithinyear rules

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-rules#11]
Some periodwithinyear rules may be applicable to all stages of the species to which they apply. In this case, the "stage" attribute of the periodwithinyear.csv file can be populated with an asterisk to indicate a wildcard - i.e. the rule will apply to all records of the species regardless of which stage term may be linked to them, or if there is no stage attribute at all.

@JimBacon to ensure that the record cleaner code allows for this.

@robin-hutchinson I'm only aware of one example that this currently applies to, which is the [periodwithinyear rules for the British Phycological Society](https://github.com/BiologicalRecordsCentre/record-cleaner-rules/blob/txt_to_csv/rules_as_csv/British%20Phycological%20Society/BPS/periodwithinyear.csv). In that file, under the stage attribute, please can you replace "mature" with an asterisk. This will also provide us with a test case that we can use.

**Comment by robin-hutchinson** [comment]
Done! https://github.com/BiologicalRecordsCentre/record-cleaner-rules/blob/txt_to_csv/rules_as_csv/British%20Phycological%20Society/BPS/periodwithinyear.csv
