### ISSUE TITLE
Use of ancillary rules within iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-rules#4]
@Sam-Amy to investigate whether ancillary rules are implemented in iRecord.

This is now donw: we have the ancillary (rarity) rules in the Indicia infrastructure but we have not implemented their use in iRecord, i.e. they are not displayed as a rule check icon nor can they be used for filtering.

**Comment by kitenetter** [comment]
No need to pursue this any further for now, but it's something we can start to ask verifiers about and work out if there is a good case for spending time on implementing the rarity rules.

**Comment by kitenetter** [comment]
Note to self - I think the ancillary rules are being displayed for at least some taxa (e.g. Stratiomys chamaeleon) but not sure why I haven't been able to find them in all cases. (Note that I am assuming the check labelled "requires additional verification" is an ancillary rule - I don't know if that is the case.)

They are not available to verifiers for filtering purposes.

**Comment by JimBacon** [comment]
Certainly _Stratiomys chamaeleon_, with NBN TVK NBNSYS0000007839, features in the Additional Rules file, 
See https://warehouse1.indicia.org.uk/index.php/verification_rule/edit/27939

**Comment by kitenetter** [comment]
Thanks @JimBacon - I couldn't remember if "additional" was the same as "ancillary" but it seems it is.
