### ISSUE TITLE
Add permissions for this repository

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-rules#7]
@JimBacon please can you add appropriate permissions to @kitenetter @Sam-Amy and @robin-hutchinson so that we can assign and label issues in this repository.

**Comment by JimBacon** [comment]
I've given you Admin permissions, @kitenetter, so you can add/modify permissions in future.
@Sam-Amy and @robin-hutchinson, I've given you Write permissions so you can update the repository contents.
