### ISSUE TITLE
Handling of stage terms for rule checks

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-rules#8]
Some possible (and speculative) approaches:

We wish to enable rules to be applied to the correct stages where this is relevant to the taxon group concerned. E.g. separate phenology rules for butterfly adults and caterpillars.

Complexities arise due to:
1. the terminology used to describe life stages varies from taxon group to taxon group, and is often inconsistently applied with taxon groups
2. for those groups that have a readily recognised adult stage it may be reasonably straightforward to define rules that are intended to apply only to the adults, but the early stages may require rules for caterpillars, or pupae, or leaf-mines etc.

A good start to resolving this could be made if we were able to divide stage terms into "mature" and "immature". Within the Indicia data warehouse this binary categorisation could in principle be added as an attribute for each stage term in the warehouse (or at least for each stage term in the major data sources). This would require a change to the data model for stage terms generally, and quite a lot of editing work to add appropriate categories to existing stage terms.

Rules could then be defined as applying to "mature" or "immature" stages, and linked accordingly.

There would need to be a default behaviour specified to deal with records that arrive either with no stage term, or else with a stage term that has not been categorised.

The above would facilitate stage-appropriate checking in Indicia, but for the web-based record cleaner we also need to make this available to data coming in from other sources. We could provide guidance to users to include a mature/immature categorisation in their source data.

Questions:
1. Instead of 'hard-coding' the mature/immature categorisation into the data sources, would it be possible to run a check on incoming data that uses some sort of text fuzzy matching to match the most frequent terms against the mature/immature categorisation? E.g. we might say that these terms are all "mature": adult | adults | flowering | in flower etc. And these are all "immature": larva | larvae | caterpillar | egg | pupa | seedling | young | immature etc. etc.
2. What should we do with records that have no stage? The only realistic option is to treat them as "mature" since that is what most people record most of the time.

**Comment by JimBacon** [comment]
From the point of view of the record cleaner service, whatever situation exists in Indicia is not necessarily our problem.

What the record cleaner service has to do is match the stage given to a record with the stages used by the rules for that species. It would be quite happy having different sets of stage terms for different species groups. We could add some new validation to check when records use unrecognised stage terms. 

What are the needs and expectations of our users? Would rules for immature/mature be adequate for them? If so, matching multiple terms on to immature and mature would be no problem.

With regard to records with no stage, another option is to use the earliest date for any stage to the latest date. This is the most permissive option while your suggestion is the least permissive. Yours is probably more useful though (and might encourage the recording of stage).

We will need a definitive specification to implement this feature.

**Comment by kitenetter** [comment]
The next steps are:
- Robin to edit all existing periodwithinyear.csv files to populate the stage column with "mature" rather than "Adult"
- Robin to complete the transfer of the remaining rules into csv format:
   - For Hoverflies we can use the default flight periods and ignore any additional sex and stage definitions under the [Data] subheading
   - For Plume moths the rules seems to be ready to transfer - were there any other questions over these?
   - For Spiders we can use the default flight periods and ignore any additional sex and stage definitions under the [Data] subheading
- Martin to define a file "stage_synonyms.csv" for each set of rules

**Comment by robin-hutchinson** [comment]
I've added those files - ok to close?

**Comment by kitenetter** [comment]
I think this is all done - closing
